### ISSUE TITLE
FamilyActivityPicker  apps is empty, just show category

### ISSUE THREAD

**Issue by AHaManz** [CoffeeNaeriRei/ScreenTime_Barebones#41]
<img width="391" alt="image" src="https://github.com/CoffeeNaeriRei/ScreenTime_Barebones/assets/14139472/81879714-758d-4d72-91f1-2cfc11e86b3b">

apps is empty, just show category

**Comment by kybeen** [comment]
Hello @AHaManz.

If you build with the `Xcode simulator` you won't be able to see apps by category in the FamilyActivityPicker. I also experienced the same issue during development.
I don't know why, but it seems like we can see apps by category in the FamilyActivityPicker only when we build it with **`"Real Device"`**.

If you must use a simulator rather than a real device, **there is one way** to check whether Screen Time's blocks are working properly or not.
👉 Select `All Apps & Categories` (the top item) in the simulator's FamilyActivityPicker and start app blocking. This will block all apps in the simulator.

<img src="https://github.com/CoffeeNaeriRei/ScreenTime_Barebones/assets/89764127/8fdc53f5-59bb-4a81-92a1-4f82fcc1b15e" height="400">

**Comment by AHaManz** [comment]
Thank you for your answer. I understand now
